spring:
  redis:
    host: localhost
    password:
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ASas940916.
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
