server:
  port: 8080

spring:
  datasource:
    username: root
    password: ASas940916.
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver


#showSql
logging:
  level:
    com:
      example:
        mapper: debug
