server:
  port: 8081

spring:
  datasource:
    username: root
    password: ASas940916.
    url: jdbc:mysql://localhost:3306/rdyl_db?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: localhost
    port: 6379
    password:
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: /static/**
  thymeleaf:
    cache: false
    encoding: utf-8
    suffix: .html
    prefix: classpath:/templates/
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 10MB
#showSql
logging:
  level:
    com:
      example:
        mapper: debug
  path: output/logs
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis/*.xml