server:
  port: 8081

spring:
  datasource:
    username: rdylroot
    password: ASas940916!
    url: jdbc:mysql://rm-m5e127mjd04uz2f8w.mysql.rds.aliyuncs.com:3306/rdyl_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: r-m5e7xf4dy7dj09l0fy.redis.rds.aliyuncs.com
    port: 6379
    password: ASas940916
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: /static/**
  thymeleaf:
    cache: false
    encoding: utf-8
    suffix: .html
    prefix: classpath:/templates/
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 10MB
#showSql
logging:
  level:
    com:
      example:
        mapper: debug
  path: output/logs
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis/*.xml